INSERT INTO positions (position_name) VALUES
                                          ('Cloud Architect'),
                                          ('Site Reliability Engineer'),
                                          ('Data Scientist'),
                                          ('Big Data Engineer'),
                                          ('Database Administrator'),
                                          ('Quality Assurance Engineer'),
                                          ('Automation Test Engineer'),
                                          ('Security Engineer'),
                                          ('UI/UX Developer'),
                                          ('API Developer'),
                                          ('Systems Engineer'),
                                          ('Performance Engineer'),
                                          ('Embedded Systems Developer'),
                                          ('Game Developer'),
                                          ('Blockchain Developer'),
                                          ('AI Engineer'),
                                          ('Infrastructure Engineer'),
                                          ('Solutions Architect'),
                                          ('Scrum Master'),
                                          ('Product Owner');